name: rick_and_morty
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  dio: ^5.7.0
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  json_annotation: ^4.9.0
  logger: ^2.4.0
  retrofit: ^4.4.1

dev_dependencies:
  build_runner: ^2.4.12
  json_serializable: ^6.8.0
  retrofit_generator: ^9.1.2
  very_good_analysis: ^6.0.0

flutter:
  uses-material-design: true
